name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_stable:
    name: Build and test stable
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          # - beta
          # - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: cargo build --verbose --no-default-features
      - run: cargo test --verbose --no-default-features

  build_and_test_nightly:
    name: Build and test nightly
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          # - stable
          # - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update nightly && rustup default nightly
      - run: cargo build --verbose
      - run: cargo test --verbose
